- manifest.php
- models/classes/theme/LtiClientThemeConfig.php
- models/classes/theme/LtiThemeSwitcher.php
- scripts/update/class.Updater.php
depends on
* https://github.com/oat-sa/tao-core/pull/895
* https://github.com/oat-sa/tao-core/pull/896
> Added theme switchign capabilities

- actions/class.ToolModule.php
- actions/traits/LtiModuleTrait.php
- manifest.php
- models/classes/class.LtiException.php
- scripts/update/class.Updater.php
https://oat-sa.atlassian.net/browse/TAO-4032
> LTI Error handling - Too much information in error returned URL

- actions/class.ToolModule.php
- actions/traits/LtiModuleTrait.php
- manifest.php
- scripts/update/class.Updater.php
https://oat-sa.atlassian.net/browse/TAO-4495
> Fixed redirect if failed signature

- manifest.php
- models/classes/class.LtiUtils.php
- models/classes/user/LtiUser.php
- models/classes/user/OntologyLtiUserService.php
- scripts/update/class.Updater.php
- test/OauthTest.php
> Release 4.2.0

- manifest.php
- scripts/update/Updater.php
> Release 6.0.1

- manifest.php
- models/classes/user/KvLtiUserService.php
- models/classes/user/LtiUserService.php
- models/classes/user/OntologyLtiUserService.php
- scripts/update/Updater.php
> Release 6.3.0

- controller/CookieUtils.php
- controller/ToolModule.php
- manifest.php
- scripts/update/Updater.php
> Release 6.3.3

- config/default/auth.conf.php
- manifest.php
- models/classes/LtiAuthAdapter.php
- models/classes/LtiLaunchData.php
- models/classes/LtiService.php
- models/classes/user/LtiUser.php
- scripts/update/Updater.php
https://oat-sa.atlassian.net/browse/TAO-6742
> Tao 6742/configuratble lti auth

- config/default/auth.conf.php
- manifest.php
- models/classes/LtiAuthAdapter.php
- models/classes/LtiLaunchData.php
- models/classes/LtiService.php
- models/classes/user/LtiUser.php
- scripts/update/Updater.php
> Release 6.4.0

- config/default/UserService.conf.php
- manifest.php
- models/classes/user/KvLtiUser.php
- models/classes/user/UserService.php
- scripts/update/Updater.php
Depends on https://github.com/oat-sa/tao-core/pull/1868
https://oat-sa.atlassian.net/browse/TAO-7144
> Fix/tao 7144/fix testtakernames

- config/default/UserService.conf.php
- controller/LtiModule.php
- manifest.php
- models/classes/user/KvLtiUser.php
- models/classes/user/UserService.php
- scripts/update/Updater.php
> Release 7.3.0

- manifest.php
- models/classes/LtiException.php
- scripts/update/Updater.php
In case of customer app not set, the exception message it's not displayed.
> Fix/tao 7084/concate lti messages

- manifest.php
- models/classes/LtiException.php
- scripts/update/Updater.php
> Release 8.0.1

- config/default/UserService.conf.php
- manifest.php
- scripts/update/Updater.php
> Release 8.0.3

- manifest.php
- scripts/tools/SetupLtiConsumer.php
- scripts/update/Updater.php
> Release 8.6.0

- manifest.php
- models/classes/LtiLaunchData.php
- scripts/update/Updater.php
Created constant for LTI Context Title parameter
> Feature/tao 7389/add lti context title constant

- config/default/ConsumerService.conf.php
- config/default/ProviderService.conf.php
- controller/ConsumerAdmin.php
- controller/ProviderAdmin.php
- controller/structures.xml
- install/ontology/lti.rdf
- manifest.php
- models/classes/ConsumerService.php
- models/classes/ProviderService.php
- scripts/update/Updater.php
- test/unit/models/classes/ConsumerServiceTest.php
- test/unit/models/classes/ProviderServiceTest.php
Provided:
- LTI Providers management feature
- refactor of LTI provider + consumer controller and services
- related unit tests
- bump to version 9.1.0
=> https://oat-sa.atlassian.net/browse/NEX-63
> LTI providers management

- README.md
- manifest.php
- scripts/update/Updater.php
https://oat-sa.atlassian.net/browse/TAO-8616
> Configuration options documented

- controller/ProviderAdmin.php
Lti Provider Admin needed an update.
> Replaced admin LtiProvider service.

- manifest.php
- models/classes/LtiProvider/ConfigurableLtiProviderRepository.php
- models/classes/LtiProvider/LtiProviderRepositoryInterface.php
- models/classes/LtiProvider/LtiProviderService.php
- models/classes/LtiProvider/RdfLtiProviderRepository.php
- scripts/update/Updater.php
- test/unit/models/classes/LtiProvider/LtiProviderServiceTest.php
https://oat-sa.atlassian.net/browse/NEX-311
> Allows to search provider by his ID

- manifest.php
- models/classes/LtiProvider/ConfigurableLtiProviderRepository.php
- models/classes/LtiProvider/LtiProviderRepositoryInterface.php
- models/classes/LtiProvider/LtiProviderService.php
- models/classes/LtiProvider/RdfLtiProviderRepository.php
- scripts/update/Updater.php
https://oat-sa.atlassian.net/browse/NEX-311
Fixed an issue with handling non-existent rdf resource
> Fix/nex 311/rdf implementation

- manifest.php
- models/classes/LtiProvider/ConfigurableLtiProviderRepository.php
- models/classes/LtiProvider/LtiProviderRepositoryInterface.php
- models/classes/LtiProvider/LtiProviderService.php
- models/classes/LtiProvider/RdfLtiProviderRepository.php
- scripts/update/Updater.php
- test/unit/models/classes/LtiProvider/LtiProviderServiceTest.php
> Release 10.4.1

- controller/ToolModule.php
- manifest.php
- models/classes/LtiLaunchData.php
- scripts/update/Updater.php
- test/unit/models/classes/LtiLaunchDataTest.php
This reverts the wrong part in the PR https://github.com/oat-sa/extension-tao-lti/pull/198/files.
> Fixed wrong PR.

- controller/ToolModule.php
- manifest.php
- scripts/update/Updater.php
Added functionality to log lti params
To test: Run lti test. Check logs.
> Feature/nfersup 25/logging lti param

- controller/ToolModule.php
- manifest.php
- scripts/update/Updater.php
> NFERSUP-25 - added logger for lti launch params.changed log method

- config/default/CookieVerifyService.conf.php
- controller/ToolModule.php
- manifest.php
- models/classes/user/KvLtiUserService.php
- models/classes/user/LtiUserFactoryService.php
- models/classes/user/OntologyLtiUserService.php
- scripts/tools/OntologyLtiUserToKvMigration.php
- scripts/update/Updater.php
- test/unit/models/classes/user/LtiUserFactoryServiceTest.php
> Release 10.7.0

- controller/ToolModule.php
- manifest.php
- scripts/update/Updater.php
Backport https://github.com/oat-sa/extension-tao-lti/pull/207 to sprint 111
> NFERSUP-25

- config/default/LisOauthService.conf.php
- manifest.php
- models/classes/Lis/LisAuthAdapter.php
- models/classes/Lis/LisAuthAdapterException.php
- models/classes/Lis/LisAuthAdapterFactory.php
- models/classes/Lis/LisOAuthConsumer.php
- models/classes/Lis/LisOauthDataStore.php
- models/classes/Lis/LisOauthService.php
- models/classes/Lis/LisSignatureValidator.php
- models/classes/Lis/LtiProviderUser.php
- models/classes/LtiAuthAdapter.php
- models/classes/LtiProvider/ConfigurableLtiProviderRepository.php
- models/classes/LtiProvider/LtiProvider.php
- models/classes/LtiProvider/LtiProviderRepositoryInterface.php
- models/classes/LtiProvider/LtiProviderService.php
- models/classes/LtiProvider/RdfLtiProviderRepository.php
- scripts/tools/OntologyLtiUserToKvMigration.php
- scripts/update/Updater.php
- test/unit/models/classes/Lis/LisAuthAdapterTest.php
- test/unit/models/classes/Lis/LisOAuthConsumerTest.php
- test/unit/models/classes/Lis/LisOauthDataStoreTest.php
- test/unit/models/classes/Lis/LtiProviderUserTest.php
- test/unit/models/classes/LtiProvider/ConfigurableLtiProviderRepositoryTest.php
- test/unit/models/classes/LtiProvider/LtiProviderServiceTest.php
- test/unit/models/classes/LtiProvider/LtiProviderTest.php
- test/unit/models/classes/LtiProvider/RdfLtiProviderRepositoryTest.php
- test/unit/models/classes/LtiProvider/_resources/lti_provider_list.json
> Release 11.1.1

- manifest.php
- models/classes/LtiLaunchData.php
- models/classes/LtiService.php
- scripts/update/Updater.php
- test/unit/models/classes/LaunchDataTest.php
> Release 11.2.0

- manifest.php
- scripts/update/Updater.php
- test/unit/models/classes/Lis/LisOauthDataStoreTest.php
> Release 11.2.1

- manifest.php
- scripts/update/Updater.php
- test/integration/OauthTest.php
- test/integration/RestServiceTest.php
- test/unit/models/classes/LtiLaunchDataTest.php
- test/unit/models/classes/LtiProvider/ConfigurableLtiProviderRepositoryTest.php
- test/unit/models/classes/LtiProvider/LtiProviderServiceTest.php
- test/unit/models/classes/LtiProvider/RdfLtiProviderRepositoryTest.php
related to: https://oat-sa.atlassian.net/browse/TDR-1
depends on: https://github.com/oat-sa/generis/pull/751
Upgrade to phpunit8
> Feature/tdr 1/phpunit8 upgrade

- config/default/SecretKeyService.conf.php
- controller/ConsumerAdmin.php
- controller/ToolModule.php
- controller/structures.xml
- manifest.php
- models/classes/LtiAuthAdapter.php
- models/classes/Security/Business/Contract/SecretKeyServiceInterface.php
- models/classes/Security/Business/Domain/Exception/SecretKeyGenerationException.php
- models/classes/Security/Business/Service/SecretKeyService.php
- scripts/update/Updater.php
- test/unit/models/classes/Security/Business/Service/SecretKeyServiceTest.php
Backports:
- #230
- #232
Depends on core backport [#2454](https://github.com/oat-sa/tao-core/pull/2454).
> NFER-55: backport pentest fixes to sprint 111

- manifest.php
- models/classes/user/LtiUser.php
- scripts/update/Updater.php
> Release 11.7.2

- manifest.php
- scripts/update/Updater.php
> Release 11.8.3

- manifest.php
> remove strict types broken build

- manifest.php
- models/classes/user/events/LtiBackOfficeUserCreatedEvent.php
- models/classes/user/events/dispatcher/LtiUserEventDispatcher.php
- test/unit/models/classes/user/events/LtiBackOfficeUserCreatedEventTest.php
- test/unit/models/classes/user/events/dispatcher/LtiUserEventDispatcherTest.php
This PR aims to prepare webhook for lti backoffice user.
> Feature/nex 1094/backoffice user metrics

- composer.json
- controller/Security.php
- doc/rest.json
- manifest.php
- migrations/Version202008040720233772_taoLti.php
New JWKS endpoint for LTI1.3
https://oat-sa.atlassian.net/browse/NEX-1532
> add new jwks endpoint

- composer.json
- config/default/KeyChainGenerator.conf.php
- manifest.php
- migrations/Version202008131228163772_taoLti.php
- models/classes/Platform/Repository/Lti1p3RegistrationRepository.php
- models/classes/Platform/Service/CachedKeyChainGenerator.php
- models/classes/Platform/Service/KeyChainGenerator.php
- models/classes/Platform/Service/KeyChainGeneratorInterface.php
- models/classes/Security/DataAccess/Repository/CacheKeyChainRepository.php
- models/classes/Security/DataAccess/Repository/CachedPlatformJwksRepository.php
- models/classes/Security/DataAccess/Repository/CachedPlatformKeyChainRepository.php
- scripts/install/GenerateKeys.php
- test/unit/models/classes/Platform/Repository/Lti1p3RegistrationRepositoryTest.php
- test/unit/models/classes/Platform/Service/CachedKeyChainGeneratorTest.php
- test/unit/models/classes/Platform/Service/KeyChainGeneratorTest.php
- test/unit/models/classes/Security/DataAccess/Repository/CacheKeyChainRepositoryTest.php
- test/unit/models/classes/Security/DataAccess/Repository/CachedPlatformJwksRepositoryTest.php
wrong base merge : https://github.com/oat-sa/extension-tao-lti/pull/263
> Feature/nex 1534/jwks service

- manifest.php
- models/classes/LtiOutcome/LtiOutcomeXmlFactory.php
- test/unit/models/classes/LtiOutcome/LtiOutcomeXmlFactoryTest.php
Fix/tao 9835/fix replace result namespace
> Fix/tao 9835/fix replace result namespace

- manifest.php
- models/classes/LtiOutcome/LtiOutcomeXmlFactory.php
- test/unit/models/classes/LtiOutcome/LtiOutcomeXmlFactoryTest.php
> Release 11.12.0

- models/classes/LtiProvider/LtiProviderFactory.php
- models/classes/Platform/Service/Oidc/Lti1p3UserAuthenticator.php
- models/classes/Tool/Factory/Lti1p3LaunchRequestFactory.php
- models/classes/Tool/LtiLaunchCommand.php
- models/classes/Tool/LtiLaunchCommandInterface.php
- test/unit/models/classes/Platform/Service/Oidc/Lti1p3UserAuthenticatorTest.php
- test/unit/models/classes/Tool/Factory/Lti1p3LaunchRequestFactoryTest.php
- test/unit/models/classes/Tool/LtiLaunchCommandTest.php
Make OIDC mandatory
https://oat-sa.atlassian.net/browse/NEX-1858
> Make OIDC mandatory

- manifest.php
- test/unit/models/classes/Security/AuthorizationServerFactoryTest.php
Change use block to relocate NoPrivacy trait
> fix use to change NoPrivacy trait location

- composer.json
- manifest.php
- models/classes/Platform/Service/Oidc/Lti1p3OidcLoginAuthenticator.php
- models/classes/Tool/Factory/Lti1p3LaunchRequestFactory.php
- test/unit/models/classes/Platform/Repository/Lti1p3RegistrationRepositoryTest.php
- test/unit/models/classes/Platform/Service/Oidc/Lti1p3OidcLoginAuthenticatorTest.php
- test/unit/models/classes/Tool/Factory/Lti1p3LaunchRequestFactoryTest.php
- test/unit/models/classes/Tool/Service/Lti1p3LauncherTest.php
Update LTI core Library
https://oat-sa.atlassian.net/browse/NEX-1859
Testable here: http://lti_1p3-integration.playground.kitchen.it.taocloud.org:48721/
> Update LTI core Library

- composer.json
- manifest.php
> Release 12.0.0

- .github/workflows/conventional_commits_check.yml
- .github/workflows/release_tao_extension.yml
> Release 12.0.1

- config/default/LtiPlatformRepository.conf.php
- controller/PlatformAdmin.php
- controller/structures.xml
- install/ontology/lti.rdf
- migrations/Version202108101321114915_taoLti.php
- models/classes/LtiProvider/ConfigurableLtiProviderRepository.php
- models/classes/LtiProvider/LtiProviderFieldsMapper.php
- models/classes/LtiProvider/LtiProviderService.php
- models/classes/LtiProvider/RdfLtiProviderRepository.php
- models/classes/LtiProvider/Validation/ValidationRegistry.php
- models/classes/Platform/LtiPlatform.php
- models/classes/Platform/Repository/Lti1p3RegistrationRepository.php
- models/classes/Platform/Repository/LtiPlatformFactory.php
- models/classes/Platform/Repository/LtiPlatformRepositoryInterface.php
- models/classes/Platform/Repository/RdfLtiPlatformRepository.php
- models/classes/Platform/Validation/ValidationRegistry.php
- models/classes/Platform/Validation/ValidatorsFactory.php
- models/classes/Security/AccessTokenRequestValidator.php
- test/unit/models/classes/LtiProvider/LtiProviderServiceTest.php
- test/unit/models/classes/Platform/LtiPlatformTest.php
- test/unit/models/classes/Platform/Repository/Lti1p3RegistrationRepositoryTest.php
- test/unit/models/classes/Platform/Service/AccessTokenRequestValidatorTest.php
- test/unit/models/classes/Security/AuthorizationServerFactoryTest.php
> Release 12.2.0

- controller/Security.php
- controller/ToolModule.php
- models/classes/LtiProvider/RdfLtiProviderRepository.php
- models/classes/Platform/Repository/Lti1p3RegistrationRepository.php
- models/classes/Platform/Repository/RdfLtiPlatformRepository.php
- models/classes/Tool/Validation/Lti1p3Validator.php
- test/integration/models/classes/Tool/Validation/Lti1p3ValidatorTest.php
> Release 13.1.0

- composer.json
- install/ontology/ltiroles_membership.rdf
- migrations/Version202109230814043772_taoLti.php
- models/classes/LtiLaunchData.php
- models/classes/LtiRoles.php
- models/classes/LtiService.php
- models/classes/TaoLti1p3Session.php
- models/classes/user/Lti1p3User.php
- test/unit/models/classes/user/Lti1p3UserTest.php
> Release 13.2.0

- controller/ToolModule.php
> Release 13.2.1

- models/classes/LtiLaunchData.php
> Release 15.3.0

- install/ontology/ltiroles_membership.rdf
- migrations/Version202111040844153772_taoLti.php
related to https://oat-sa.atlassian.net/browse/TR-1919
required for https://github.com/oat-sa/extension-lti-test-review/pull/92
> fix: adding to ontology roles lit new lti1p3 roles

- install/ontology/ltiroles_membership.rdf
- migrations/Version202111040844153772_taoLti.php
> Release 15.4.1

- README.md
- composer.json
- models/classes/Client/LtiClientFactory.php
- models/classes/LtiAgs/LtiAgsScoreService.php
- models/classes/ServiceProvider/LtiServiceProvider.php
- test/unit/models/classes/LtiAgsScoreServiceTest.php
> Release 15.5.0

- composer.json
- scripts/install/MapLtiSectionVisibility.php
> Release 15.6.0

- migrations/Version202009241529173772_taoLti.php
- scripts/install/MapLtiSectionVisibility.php
> Release 15.6.1

- models/classes/LtiLaunchData.php
> Release 15.6.2

- install/ontology/ltiroles_membership.rdf
- migrations/Version202204051020153772_taoLti.php
Related to [MS-2021](https://oat-sa.atlassian.net/browse/MS-2021).
Add new permissions to the LTI Role Instructor for previewing QTI items
> fix: add the QTI Manager permission to the Instructor profile

- install/ontology/ltiroles_membership.rdf
- migrations/Version202204051020153772_taoLti.php
> Release 15.8.1

- manifest.php
- migrations/Version202203081458463772_taoLti.php
- models/classes/Platform/Repository/Lti1p3RegistrationSnapshotSchemaProvider.php
- scripts/install/CreateLti1p3RegistrationSnapshotSchema.php
> Release 15.8.2

- .github/workflows/continuous-integration.yaml
- README.md
> Release 15.8.3

- models/classes/user/Lti1p3User.php
- models/classes/user/LtiUser.php
- test/unit/models/classes/LtiAgsScoreServiceTest.php
- test/unit/models/classes/user/Lti1p3UserTest.php
> Release 15.9.0

- manifest.php
- migrations/Version202209261307433772_taoLti.php
- scripts/install/SetupServices.php
Jira task is [REL-842](https://oat-sa.atlassian.net/browse/REL-842)
- fix: add extension to generis whitelist for search
- chore: add migration
> Disable advanced search for the extension

- manifest.php
- migrations/Version202209261307433772_taoLti.php
- scripts/install/SetupServices.php
> Release 15.9.1

- .github/workflows/continuous-integration.yaml
- composer.json
- models/classes/LtiProvider/Validation/LtiProviderValidator.php
- test/unit/models/classes/LtiAgsScoreServiceTest.php
> Release 15.9.2

- models/classes/LtiLaunchData.php
- test/unit/models/classes/LtiLaunchDataTest.php
> Release 15.11.0

- models/classes/LtiException.php
Rollback translated string
[ADF-1440]: https://oat-sa.atlassian.net/browse/ADF-1440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: rollback translated strings and ignore PSR-12 for them

- models/classes/LtiException.php
> Release 15.11.3

- install/ontology/ltiroles_membership.rdf
> Release 15.13.1

- models/classes/LtiProvider/LtiProviderService.php
- test/unit/models/classes/LtiProvider/LtiProviderServiceTest.php
> Release 15.13.2

- models/classes/LtiProvider/LtiProviderService.php
- test/unit/models/classes/LtiProvider/LtiProviderServiceTest.php
Related to ticket https://oat-sa.atlassian.net/browse/REL-1164
> Backport/rel 1164/lti provider registration

- controller/AuthoringTool.php
Refs: https://github.com/oat-sa/extension-tao-lti/pull/392
> [BACKPORT] [SOLAR-387] Add fallback when no registration available

- install/ontology/ltiroles_membership.rdf
https://oat-sa.atlassian.net/browse/ADF-1842
- Add Item and Test translator roles for the users coming from Portal
> feat: add translator role for users coming from portal
