oat-sa/extension-tao-lti

manifest.php
models/classes/theme/LtiHeadless.php
models/classes/theme/LtiThemeSwitcher.php
scripts/update/class.Updater.php

Related to: https://oat-sa.atlassian.net/browse/TAO-3849
Add an option to remove the header and the footer from pages displayed in LTI mode.

Add option to remove header/footer from pages

---

models/classes/theme/LtiThemeSwitcher.php

Related to: https://oat-sa.atlassian.net/browse/TAO-3849
Add detection for both `frame` and `iframe` targets.

Take care of all frame targets in headless detection

---

config/default/LtiUserService.conf.php
manifest.php
models/classes/user/OntologyLtiUserService.php
scripts/update/class.Updater.php

**DEPENDS ON https://github.com/oat-sa/generis/pull/415**
You can turn on the `transaction-safe` mode for the Ontology Implementation by changing the value of the `transaction-safe` parameter in `/config/taoLti/LtiUserService.conf.php` e.g. 
```php
return new oat\taoLti\models\classes\user\OntologyLtiUserService(array(
'transaction-safe' => true,
'transaction-safe-retry' => 1
));
```

Transaction-safe option.

---

manifest.php
scripts/update/Updater.php
views/templates/error.tpl

task https://oat-sa.atlassian.net/browse/TAO-8156
- replaced `jquery-ui-1.8.22` which is not exists anymore by `jquery-ui-1.9.2` (new version of library)

Fix/tao 8156/updated jquery ui css path

---

manifest.php
models/classes/user/KvLtiUserService.php
models/classes/user/LtiUserService.php
models/classes/user/OntologyLtiUserService.php
models/classes/user/events/LtiUserCreatedEvent.php
models/classes/user/events/LtiUserEvent.php
models/classes/user/events/LtiUserUpdatedEvent.php
scripts/update/Updater.php

Pull request summary
Related to: https://oat-sa.atlassian.net/browse/TAO-8585
New events added to have a possibility to listen when lti user changed:
- added LtiUserUpdatedEvent
- added LtiUserCreatedEvent
You can test it with the taoSyncClient extension (https://github.com/oat-sa/extension-tao-sync-client/tree/develop)
taoSyncClient creates `sync_client_queue` table and add new rows on lti user update action

added LtiUser events (create and update)

---

config/default/LtiProviderService.conf.php
manifest.php
scripts/update/Updater.php

fix for https://oat-sa.atlassian.net/browse/NEX-256
1. The version of TAO after the installation has to be equal to the version of TAO after Update (in this case - it's a different configuration of the service)
2. Fixed updater - if service new it has to be created, service can't be updated if it does not exist.

Fix/nex 256/fixed updater and installer

---

scripts/update/Updater.php

- TBD-8 fix(updater): replace usage of `OauthService::OPTION_DATASTORE` with a proper `OPTION_DATA_STORE` in `Updater` script
That line wasn't considered to be a conflicting one of course, as it was just added in one of the recent PRs.

TBD-8 post-merge quickfix of updater script

---

config/default/LisOauthService.conf.php
manifest.php
scripts/update/Updater.php

https://oat-sa.atlassian.net/browse/NEX-1228
This PR fixes an issue in LisOauthService that the `lockout` sub-service was not defined which is inherited from `OauthService`.

added lockout subservice to LisOauthService

---

composer.json
config/default/KeyChainGenerator.conf.php
manifest.php
migrations/Version202008131228163772_taoLti.php
models/classes/Platform/Repository/Lti1p3RegistrationRepository.php
models/classes/Platform/Service/CachedKeyChainGenerator.php
models/classes/Platform/Service/KeyChainGenerator.php
models/classes/Platform/Service/KeyChainGeneratorInterface.php
models/classes/Security/DataAccess/Repository/CacheKeyChainRepository.php
models/classes/Security/DataAccess/Repository/CachedPlatformJwksRepository.php
models/classes/Security/DataAccess/Repository/CachedPlatformKeyChainRepository.php
scripts/install/GenerateKeys.php
test/unit/models/classes/Platform/Repository/Lti1p3RegistrationRepositoryTest.php
test/unit/models/classes/Platform/Service/CachedKeyChainGeneratorTest.php
test/unit/models/classes/Platform/Service/KeyChainGeneratorTest.php
test/unit/models/classes/Security/DataAccess/Repository/CacheKeyChainRepositoryTest.php
test/unit/models/classes/Security/DataAccess/Repository/CachedPlatformJwksRepositoryTest.php

Created service responsible for the generation of JWK public and private keys. 
Including cache using KeyChainRepositoryInterface implementation
https://oat-sa.atlassian.net/browse/NEX-1534
To test this functionality you may use:
`https://{tao-url}/taoLti/Security/jwks`
Before you use is please install or update your instance in order to generate required `keyChains`.

Feature/nex 1534/jwks service

---

controller/KeyChainView.php
controller/Security.php
manifest.php
models/classes/LtiProvider/LtiProvider.php
models/classes/Platform/Repository/Lti1p3RegistrationRepository.php
models/classes/Security/AuthorizationServer/AuthorizationServerFactory.php
models/classes/Security/DataAccess/Repository/CachedPlatformKeyChainRepository.php
models/classes/Security/DataAccess/Repository/PlatformKeyChainRepository.php
models/classes/Security/DataAccess/Repository/ToolKeyChainRepository.php
test/unit/models/classes/Platform/Repository/Lti1p3RegistrationRepositoryTest.php
test/unit/models/classes/Security/AuthorizationServerFactoryTest.php
test/unit/models/classes/Security/DataAccess/Repository/CachedPlatformKeyChainRepositoryTest.php
test/unit/models/classes/Security/DataAccess/Repository/PlatformKeyChainRepositoryTest.php
test/unit/models/classes/Security/DataAccess/Repository/ToolKeyChainRepositoryTest.php

Ticket : https://oat-sa.atlassian.net/browse/NEX-1952
Requires : oat-sa/generis#840
- Allow lti13 platform registration to be configured with JwksToolUrl based and toolKeyChain
- Inject cache to lib-core-lti13
- fix cache by adding default identifier
- Alter default value for publicKey to respect php interface

Feature/nex 1952/support tool jwks

---

models/classes/LtiProvider/Validation/ValidationRegistry.php

This change fixes this error:
```Fatal error: Uncaught TypeError: Argument 1 passed to tao_helpers_form_FormElement::addValidator() must implement interface oat\oatbox\validator\ValidatorInterface, null given, called in /tao/code/tao/helpers/form/class.FormElement.php on line 398 and defined in /tao/code/tao/helpers/form/class.FormElement.php:380 Stack trace: #0 /tao/code/tao/helpers/form/class.FormElement.php(398): tao_helpers_form_FormElement->addValidator(NULL) #1 /tao/code/tao/helpers/form/class.FormContainer.php(202): tao_helpers_form_FormElement->addValidators(Array) #2 /tao/code/tao/helpers/form/class.FormContainer.php(101): tao_helpers_form_FormContainer->applyAdditionalValidationRules(Array) #3 /tao/code/tao/actions/form/class.CreateInstance.php(69): …
```

Fix validators names

---

models/classes/LtiProvider/LtiProviderFactory.php

This errror may be encounter when searching for ltiProviders. 
`\oat\taoLti\models\classes\LtiProvider\LtiProviderFactory::getLtiVersion` 
We assume that propertiesValues[ltiVersion] will be a Resource but sometime is just Literal and getUri will throw an error.

Sometimes ltiVersion in propertiesValues may not be a resource

---

test/unit/models/classes/Security/AuthorizationServerFactoryTest.php

related to https://github.com/oat-sa/extension-tao-deliver-connect/pull/81 
depends on https://github.com/oat-sa/tao-core/compare/develop...fix/unit_test_helper?expand=1

Unit test helper moved to core from private extension

---

config/default/LtiPlatformRepository.conf.php
controller/PlatformAdmin.php
controller/structures.xml
install/ontology/lti.rdf
migrations/Version202108101321114915_taoLti.php
models/classes/LtiProvider/ConfigurableLtiProviderRepository.php
models/classes/LtiProvider/LtiProviderFieldsMapper.php
models/classes/LtiProvider/LtiProviderService.php
models/classes/LtiProvider/RdfLtiProviderRepository.php
models/classes/LtiProvider/Validation/ValidationRegistry.php
models/classes/Platform/LtiPlatform.php
models/classes/Platform/Repository/Lti1p3RegistrationRepository.php
models/classes/Platform/Repository/LtiPlatformFactory.php
models/classes/Platform/Repository/LtiPlatformRepositoryInterface.php
models/classes/Platform/Repository/RdfLtiPlatformRepository.php
models/classes/Platform/Validation/ValidationRegistry.php
models/classes/Platform/Validation/ValidatorsFactory.php
models/classes/Security/AccessTokenRequestValidator.php
test/unit/models/classes/LtiProvider/LtiProviderServiceTest.php
test/unit/models/classes/Platform/LtiPlatformTest.php
test/unit/models/classes/Platform/Repository/Lti1p3RegistrationRepositoryTest.php
test/unit/models/classes/Platform/Service/AccessTokenRequestValidatorTest.php
test/unit/models/classes/Security/AuthorizationServerFactoryTest.php

https://oat-sa.atlassian.net/browse/TR-879
LTI 1.3 Platforms + Registration repo implemented.
At the moment, it's not possible to test the whole workflow including the registration repository, as LTI1.3 isn't implemented, yet.
The only way is to check the UI screen is correct. Here's how to do that:
1. Log in to the BO.
2. Click the 'Gear' icon to open preferences, select 'LTI 1.3 Platform' which should show up with this PR applied.
3. Play around with CRUD on platforms etc, check the validation is implemented correctly.
Deployed on http://cgen-ltiregistrations.playground.kitchen.it.taocloud.org:42141/

feat: LTI 1.3 Platforms & registration repo implemented

---

controller/ToolModule.php

fix: destroy a pre-existing session, which may potentially contain unrelated or sensitive data, before starting an LTI one
1. Launch an LTI 1.1 delivery execution with a return URL
2. Launch another LTI 1.1 delivery execution, changing the return URL, and removing a mandatory field (Resource ID)
3. The user agent must no longer be returned to the original return URL
https://user-images.githubusercontent.com/2943256/135317052-31c4330a-f473-4ea3-91e8-bef0fb0034e7.mov

TR-2256 fix: destroy a pre-existing session before starting an LTI one

---

models/classes/Tool/Validation/Lti1p3Validator.php

Related to: https://oat-sa.atlassian.net/browse/TR-2279
It fixes this case
```
Fatal error: Uncaught TypeError: Return value of oat\taoLti\models\classes\Tool\Validation\Lti1p3Validator::validateRequest() must implement interface OAT\Library\Lti1p3Core\Message\Payload\LtiMessagePayloadInterface, null returned in /tao/code/taoLti/models/classes/Tool/Validation/Lti1p3Validator.php:62 Stack trace: #0 /tao/code/taoLti/models/classes/Tool/Validation/Lti1p3Validator.php(41): oat\taoLti\models\classes\Tool\Validation\Lti1p3Validator->validateRequest(Object(GuzzleHttp\Psr7\ServerRequest)) #1 /tao/code/taoLti/controller/ToolModule.php(147): oat\taoLti\models\classes\Tool\Validation\Lti1p3Validator->getValidatedPayload(Object(GuzzleHttp\Psr7\ServerRequest)) #2 …
```

fix: incorrect tool validation handling

---

models/classes/LtiLaunchData.php

related to: https://oat-sa.atlassian.net/browse/TR-1919
parsing for_user claim data into launchData storage
required for: https://github.com/oat-sa/extension-lti-test-review/pull/92

feat: added parsing for_user claim into launch data

---

README.md
composer.json
models/classes/Client/LtiClientFactory.php
models/classes/LtiAgs/LtiAgsScoreService.php
models/classes/ServiceProvider/LtiServiceProvider.php
test/unit/models/classes/LtiAgsScoreServiceTest.php

- fix: rely on `OAT\Library\Lti1p3Ags\Service\Score\ScoreServiceInterface` abstraction, not its implementation throghout the codebase
- chore: link the configuration files, mentioned by `README.md`
- fix: link to `FactoryLtiAuthAdapterService`, mentioned by `README.md`
- feat: initialize LTI client access-token cache
- fix: introduce an explicit dependency on `guzzlehttp/guzzle`, which has already been used in the codebase
- feat: introduce LTI client configuration
- [Launch an AGS-claim-containing delivery execution](https://devkit-oat-demo.dev.gcp-eu.taocloud.org/platform/message/launch/lti-resource-link?registration=infosignTestToolRegistration&user_list=c3po&launch_url=https://delivery.test-infosign.playground.kitchen.it.taocloud.org/ltiDeliveryProvider/DeliveryTool/launch1p3?delivery% …

Feature TR-2281 - configurable LTI client

---

composer.json
scripts/install/MapLtiSectionVisibility.php

https://oat-sa.atlassian.net/browse/ADF-877
This feature flag should not be here, but the initialization of the `SectionVisibilityFilter::SERVICE_ID` and `FeatureFlagFormPropertyMapper::SERVICE_ID` was done here instead of tao-core. taoLti is a client of those classes, therefore should only have options updated, but not registering the service for the first time.
I will open a ticket and ask @bartlomiejmarszal to fix that (https://oat-sa.atlassian.net/browse/AUT-1640), cause it will include fix other migrations and add installations scripts which will increase the scope of my task now.

chore: added settings metadata feature flag

---

migrations/Version202009241529173772_taoLti.php
scripts/install/MapLtiSectionVisibility.php

Replaced installation and update scripts to not replace existing SectionVisibilityFilter configs.

Configuration of SectionVisibilityFilter will not be replaced on install and update

---

models/classes/LtiLaunchData.php

Fix feature toggling for `custom_show_correct` and `custom_show_score` custom claims.
Related to : https://oat-sa.atlassian.net/browse/TR-3517
- take a test via LTI 1.3, take note of delivery execution id
- configure `config/ltiTestReview/DeliveryExecutionFinderService.conf.php` with:
```
<?php
return new oat\ltiTestReview\models\DeliveryExecutionFinderService(array(
'show_score' => true,
'show_correct' => true
));
```
- launch the lti test review with custom claims:
```
"https://purl.imsglobal.org/spec/lti/claim/custom": {
"execution": "<delivery_execution_id>",
"custom_show_score": false,
"custom_show_correct": false
}
```
- verify neither test taker response nor correct answer is shown

Fix / TR-3517 / custom claims to toggle review features

---

composer.json
controller/PlatformAdmin.php
controller/Security.php
migrations/Version202203081458463772_taoLti.php
migrations/Version202203101426253772_taoLti.php
models/classes/LtiService.php
models/classes/Platform/Repository/DefaultToolConfig.php
models/classes/Platform/Repository/Lti1p3RegistrationSnapshotRepository.php
models/classes/Platform/Service/UpdatePlatformRegistrationSnapshotListener.php
models/classes/ServiceProvider/LtiServiceProvider.php
models/classes/Tool/Validation/Lti1p3Validator.php

https://oat-sa.atlassian.net/browse/TR-3666
The current implementation of the LTI 1.3 platform registrations store ([Lti1p3RegistrationRepository.php](https://github.com/oat-sa/extension-tao-lti/blob/0aee2cd3de200d4727ec03861e0c81b41ddbfb3f/models/classes/Platform/Repository/Lti1p3RegistrationRepository.php)) reuses RDF store (triples), which may be quite slow when it comes down to selecting a record, based on anything but its ID.
During the OIDC launch flow, the LTI messages have to be verified, and the platform records are searched through by audience value, making the request quite slow.
This PR Introduces a dedicated table to store and retrieve the LTI 1.3 platform registrations.
- LTI 1.3 integration using TAO Terre as a Tool
1. Launch a test through LTI 1.3
- …

feat: create snapshot repository for platform registrations

---

models/classes/user/Lti1p3User.php
models/classes/user/LtiUser.php
test/unit/models/classes/LtiAgsScoreServiceTest.php
test/unit/models/classes/user/Lti1p3UserTest.php

Goal is to provide usage DEFAULT_ANONYMOUS_INTERFACE_LANG constant at lti launch by anonymous user
- install branch
- update in `config/generis.conf.php` constant `DEFAULT_ANONYMOUS_INTERFACE_LANG` by language other than defined in `DEFAULT_LANG` (for example `ja-JP`)
- launch execution through Lti 1.3 as anonymous user (no user identifier provided in launch data)
- interface language should be overwriten by `DEFAULT_ANONYMOUS_INTERFACE_LANG`

DEFAULT_ANONYMOUS_INTERFACE_LANG for anonymous user

---

controller/ToolModule.php
manifest.php

backport LTI session closing to prevent duplicate usage of lti session
for [TR-4934](https://oat-sa.atlassian.net/browse/TR-4934)

Backport closing LTI session

---

models/classes/Platform/Service/Oidc/Lti1p3UserAuthenticator.php
test/unit/models/classes/Platform/Service/Oidc/Lti1p3UserAuthenticatorTest.php

https://oat-sa.atlassian.net/browse/TR-4941
Use user login instead or URI as identifier, so it can later be user by data store + tao insights
- Launch a test from CG using LTI 1.3 and change the token contents
OIDC token
`
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjFfMCJ9.eyJodHRwczovL3B1cmwuaW1zZ2xvYmFsLm9yZy9zcGVjL2x0aS9jbGFpbS9yZXNvdXJjZV9saW5rIjp7ImlkIjoiYTc1YzllNmJhNjE5In0sImh0dHBzOi8vcHVybC5pbXNnbG9iYWwub3JnL3NwZWMvbHRpL2NsYWltL3ZlcnNpb24iOiIxLjMuMCIsImh0dHBzOi8vcHVybC5pbXNnbG9iYWwub3JnL3NwZWMvbHRpL2NsYWltL21lc3NhZ2VfdHlwZSI6Ikx0aVJlc291cmNlTGlua1JlcXVlc3QiLCJodHRwczovL3B1cmwuaW1zZ2xvYmFsLm9yZy9zcGVjL2x0aS9jbGFpbS9kZXBsb3ltZW50X2lkIjoiMSIsImh0dHBzOi8vcHVybC5pbXNnbG9iYWwub3JnL3NwZWMvbHRpL2NsYWltL3RhcmdldF9saW5rX3VyaSI6Imh0dHBzOi8vZGVsaXZlci5kb2NrZXIubG9jYWxob3N0L2FwaS92MS9hdXRoL2xh …

feat: use user login as user identity

---

models/classes/LtiLaunchData.php
test/unit/models/classes/LtiLaunchDataTest.php

For feature https://github.com/oat-sa/extension-tao-outcome/pull/232:
- JSON serialization for AGS claims property in order to store LTILaunchData

feat: store and retrieve LTI launch data

---

models/classes/LtiProvider/LtiProviderService.php
test/unit/models/classes/LtiProvider/LtiProviderServiceTest.php

New environment should be configured correctly after first install from seed. This change allows the `LtiProviderService::LTI_PROVIDER_LIST_IMPLEMENTATIONS` to be defined in a "seed friendly" way.
Related to : https://oat-sa.atlassian.net/browse/REL-1164 
- instead of usual `LtiProviderService::LTI_PROVIDER_LIST_IMPLEMENTATIONS` setup of for example:
```
return new LtiProviderService([
LtiProviderService::LTI_PROVIDER_LIST_IMPLEMENTATIONS => [
new RdfLtiProviderRepository(),
]
]);
```
update to different format without object construction:
```
return new LtiProviderService([
LtiProviderService::LTI_PROVIDER_LIST_IMPLEMENTATIONS => [
[
'class' => 'oat\\taoLti\\models\\classes\\LtiProvider\RdfLtiProviderRepository',
'options' => [],
]
]
]);
```
- behavior should remain the same

fix: lti provider service configuration change

---

models/classes/LtiService.php

Ticket: https://oat-sa.atlassian.net/browse/SOLAR-59
- if it is a new user created on the portal that never accessed TAO Authoring, the items page should be shown as default after login. Otherwise, after login, the user should be redirected to the last seen page.
https://github.com/oat-sa/extension-tao-lti/assets/11900046/b9403d6e-6281-4ac0-a416-2a78d6befdac

[FIX] [SOLAR-59] always redirect users to items as default

---

scripts/install/CreateLtiPlatformRecord.php
scripts/tools/SetupLtiPlatform.php

Script to create an Lti Platform, that could be used in the seed as a post install script.
Related to : https://oat-sa.atlassian.net/browse/REL-1275
- Run the command `php index.php "\oat\taoLti\scripts\tools\SetupLtiPlatform" --label TestPlatform --client_id test-client-id-1 --deployment_id 1 --audience https://foo.bar --token_url http://foo.bar --oidc_url http://foo.bar --jwks_url https://foo.bar`
- Verify in the backoffice Lti 1.3 Platform view that the record was created
- Test that it is possible to launch to TAO with the newly configured platform

Feat/rel 1275/script create lti platform

---

controller/AuthoringTool.php

We should redirect the user to the default login page in case:
1. The FF is not enabled
2. The LTI Platform config is missing
Please check the [bug ticket](https://oat-sa.atlassian.net/browse/SOLAR-387) for more details.
https://github.com/oat-sa/extension-tao-lti/assets/11900046/c10f57b0-ea3c-445d-a02b-058a96e034a5
https://github.com/oat-sa/extension-tao-lti/assets/11900046/637b7d20-3caa-4179-bbb4-dd232f85b97e

[FIX][SOLAR-387] Add fallback when no registration available or FF TAO_AS_A_TOOL is disabled

---

controller/AuthoringTool.php
install/ontology/ltiroles_membership.rdf
install/ontology/ltiroles_person.rdf
migrations/Version202312051317263774_taoLti.php
models/classes/LtiLaunchData.php
models/classes/LtiRoles.php
models/classes/ServiceProvider/LtiServiceProvider.php
models/classes/Tool/Exception/WrongLtiRolesException.php
models/classes/Tool/Service/AuthoringLtiRoleService.php
models/classes/user/LtiUser.php
test/unit/models/classes/Tool/Service/AuthoringLtiRoleServiceTest.php

How to reproduce:
Launch authoring tool using `devkit` [link](https://devkit.docker.localhost/platform/message/launch/lti-resource-link?registration=devkit__backoffice&user_type=list&user_list=r2d2&launch_url=http://backoffice.docker.localhost/taoLti/AuthoringTool/launch&claims=%7B%0D%0A%20%20%20%20%22https://purl.imsglobal.org/spec/lti/claim/roles%22:%20%5B%0D%0A%20%20%20%20%20%20%20%20%22http://purl.imsglobal.org/vocab/lis/v2/membership/ContentDeveloper%23ContentDeveloper%22,%0D%0A%20%20%20%20%20%20%20%20%22http://purl.imsglobal.org/vocab/lis/v2/membership/Administrator%23Developer%22%0D%0A%20%20%20%20%5D%0D%0A%7D)
Launch without allowed roles: 
- `http://purl.imsglobal.org/vocab/lis/v2/membership#Instructor`
- `http://purl.imsglobal.org/vocab/lis/v2/institution/person#Administrator`
- …

Feat/ayt 3400/launching authoring by new configurable roles

---

config/default/PlatformKeyChainRepository.conf.php
migrations/Version202402271423013774_taoLti.php
models/classes/Exception/PlatformKeyChainException.php
models/classes/Platform/Service/CachedKeyChainGenerator.php
models/classes/Platform/Service/KeyChainGeneratorInterface.php
models/classes/Platform/Service/OpenSslKeyChainGenerator.php
models/classes/Security/DataAccess/Repository/CachedPlatformKeyChainRepository.php
models/classes/Security/DataAccess/Repository/PlatformKeyChainRepository.php
scripts/tools/GenerateKeys.php
test/unit/models/classes/Platform/Service/CachedKeyChainGeneratorTest.php
test/unit/models/classes/Platform/Service/KeyChainGeneratorTest.php
test/unit/models/classes/Security/DataAccess/Repository/CachedPlatformKeyChainRepositoryTest.php
test/unit/models/classes/Security/DataAccess/Repository/PlatformJwksRepositoryTest.php
test/unit/models/classes/Security/DataAccess/Repository/PlatformKeyChainRepositoryTest.php

Ticket - https://oat-sa.atlassian.net/browse/REL-1466
Related to - https://github.com/oat-sa/tao-core/pull/3968
NCCER publish to two solar tenants
- feat: added support for several platform LTI providers
1. Configure 2 tenants to one authoring
2. Add delivery configuration for 2 tenants
```
{
"DELIVERTENANT_COUNT": "2",
"DELIVERTENANT_1_ID": "10",
"DELIVERTENANT_1_LABEL": "OAT TAO Solar Test Runner Stage", 
"DELIVERTENANT_1_CUSTOMER_ID": "10",
"DELIVERTENANT_1_LTI_1P3_AUDIENCE_URL": "https://<stack_url>",
"DELIVERTENANT_1_LTI_1P3_CREDENTIALS_0_CLIENT_ID": "tao-deliver-id_<tenant_id>",
"DELIVERTENANT_1_OAUTH_CREDENTIALS_0_KEY": "<Oauth_key>",
"DELIVERTENANT_1_OAUTH_CREDENTIALS_0_SECRET": "<Oauth_secret>",
... //other same like DELIVERTENANT_0
}
```
3. Add platform LTI key chain for 2 …

feat: publish to two solar tenants

---

composer.json
models/classes/LtiService.php
models/classes/TaoLtiSession.php

Ticket: https://oat-sa.atlassian.net/browse/MS-2756
- Added UserPilot to TAO 3.x.
- Backported to v15.15.0.1
- https://github.com/oat-sa/tao-core/pull/3967
- Install TAO Portal and TAO 3.x Authoring using NGS.
- cd nextgen-stack/tao
- composer require "oat-sa/extension-tao-lti":"dev-feature/MS-2756/add-userpilot-to-tao-3.x as 15.15.1" "oat-sa/tao-core":"dev-feature/MS-2756/add-userpilot-to-tao-3.x as 54.4.1"
- Setup TAO Portal - Authoring simplification
- Login to TAO Portal
- Go to Authoring by clicking on Content Bank
- Inspect source code

backport: MS-2756 backport to v15.15.0.1

---

composer.json
models/classes/LtiService.php
models/classes/TaoLtiSession.php

Ticket: https://oat-sa.atlassian.net/browse/MS-2756
- Added UserPilot to TAO 3.x.
- Backported to 15.17.1
- https://github.com/oat-sa/extension-tao-lti/pull/400
- https://github.com/oat-sa/tao-core/pull/3967
- Install TAO Portal and TAO 3.x Authoring using NGS.
- cd nextgen-stack/tao
- composer require "oat-sa/extension-tao-lti":"dev-feature/MS-2756/add-userpilot-to-tao-3.x as 15.15.1" "oat-sa/tao-core":"dev-feature/MS-2756/add-userpilot-to-tao-3.x as 54.4.1"
- Setup TAO Portal - Authoring simplification
- Login to TAO Portal
- Go to Authoring by clicking on Content Bank
- Inspect source code

backport: MS-2756 backport to v15.17.1

---

composer.json
models/classes/ServiceProvider/LtiServiceProvider.php

This will decorate RoleBasedContextRestrictAccess with sections that we want to hide from defined roles. 
This change requires:
https://github.com/oat-sa/tao-core/pull/3987

Feat/aut 3576/add restricted roles to role based context restrict access

---

install/ontology/ltiroles_membership.rdf

Ticket: https://oat-sa.atlassian.net/browse/SOLAR-624
1. Added missing Reviewer role to LTI 1p3 Content Developer
- Go to nextgen-app
- install Workflow extension
- Run the command: `docker exec -it nextgen_tao bash`
- Inside run: `php index.php '\oat\tao\scripts\SyncModels'`
- Log in TAO Portal with the user having Content Developer role
- Select “Content Bank” card
- Select an item
- Click “Submit item for review “ button

fix: add missing Reviewer role

---

manifest.php
migrations/Version202406060802293772_taoLti.php
models/classes/theme/PortalThemeService.php
scripts/install/RegisterPortalTheme.php

When user access to Tao 3.x from Tao Portal Tao will have back button that will lead back to Tao Portal
When user login using Tao login page we will use regular Tao Theme
https://github.com/oat-sa/extension-tao-lti/assets/16231681/05fd8d51-361c-4586-9323-d14dc3e6e98a
https://github.com/oat-sa/extension-tao-lti/assets/16231681/db12ca85-06df-4365-8ef4-8ccafbe5274e

fix: Use Session to select portal theme

---

controller/AuthoringTool.php
manifest.php
migrations/Version202406060802293772_taoLti.php
migrations/Version202406101417393772_taoLti.php
models/classes/theme/PortalThemeDetailProvider.php
scripts/install/RegisterPortalThemeDetailProvider.php
scripts/install/UnregisterLtiPortalTheme.php

This Registration cannot be executed on instances that are using `\oat\taoStyles\model\service\PersistenceThemeService`. 
PersistenceThemeService violates `\oat\tao\model\theme\ThemeServiceInterface`.

fix: remove RegisterPortalTheme introduction

---

models/classes/LtiService.php
models/classes/ServiceProvider/LtiServiceProvider.php

How to test:
1. In portal change user language to non English
2. Go to Content Bank
3. When redirected to Tao 3.x make sure language change has been applied
4. Make sure `My Settings` field is not visible
5. Logout button available under user name
https://github.com/oat-sa/extension-tao-lti/assets/16231681/bb55b34a-51e3-4235-83fd-76e7dc9c8494
Required changes in tao-core
https://github.com/oat-sa/tao-core/pull/4045

fix: use getLaunchPresentation language in Authoring

---

install/ontology/ltiroles_membership.rdf
migrations/Version202408231119303772_taoLti.php

Added `http://www.tao.lu/Ontologies/TAOItem.rdf#ItemAuthor` from LTI users to be able to edit response declarations using XML editor
How to test:
1. Install TAO 3.x with `xmlEditRp` extension
2. Setup Portal for using TAO 3.x as `Content Bank`
3. Create a user on portal with the `Content editor` role
4. Login by this user on Portal
5. Go to `Content bank` from the portal
6. Create an item with the custom response processing
7. Open `Edit Processing Rule`
8. Try to update XML

fix: add missed role ItemAuthor fro LTI Users

---

.github/workflows/continuous-integration.yaml
composer.json

This PR upgrades the `oat-sa/lib-lti1p3-*` to the latest ones
⚠️ DO NOT MERGE until it's confirmed that the deployment stacks support PHP 8 and higher ⚠️

feat!: upgrade oat-sa/lib-lti1p3-* libraries

---

.github/workflows/continuous-integration.yaml
composer.json
models/classes/ExceptionInterpreter.php
models/classes/Security/DataAccess/Repository/PlatformKeyChainRepository.php
test/unit/models/classes/Security/DataAccess/Repository/PlatformKeyChainRepositoryTest.php

Related to https://oat-sa.atlassian.net/browse/REL-1729

Update flysystem usage after upgrade

---

composer.json
controller/Security.php
models/classes/LtiReturnResponse.php

This PR aims to satisfy some ISO27001 automated tests.
dependencies:

Fix/aut 3968/bad request status code
